### ISSUE TITLE
[Bug]: Settings getting reset between updates using L4J 1.7.3

### ISSUE THREAD

**Issue by Cjnator38** [ViolaFlower/Re-Console#137] opened 2024-09-07 21:20 UTC
### What is the issue?

I'm guesssing since Legacy4J now separates it's own settings from options.txt, the options.txt used by YOSBR seems to be invalid, causing all settings to get reset.

### To Reproduce

1. Update from RC 0.8.0 Beta 7 to Beta 8
2. Options are reset to defaults

### Minecraft Version

1.21

### Re-Console Version

0.8.0 Beta 8

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by omo50** [comment] 2024-09-07 21:24
Duplicate of #133 . ill try and fix on the next beta

**Closed by omo50** 2024-09-07 21:24 UTC
Labels: bug
